### PR TITLE
SVG snagging

### PR DESCRIPTION
**Pull request by stephenwf**
Quick tidy up of the SVG bubbles, specifically when selected.
#### Before
Screenshot 2019-04-29 at 13 58 15

#### After
Screenshot 2019-04-29 at 13 52 41

Future enhancements could swap the rendering-ordering of the bubbles so that the selected bubbles are rendered first. This will avoid overlapping issues that we currently see.

### CODE REVIEW

**Comment by cjcolvar** [comment]
This looks better, but would it work to have the bubble selection black outline over the bubbles.  I'm seeing it hidden behind the bubbles in certain cases including the right side.

**Comment by stephenwf** [comment]
I think it a rounding error causing it to be slightly off, tricky since css `transform()` doesn't support floating point numbers. Maybe we need to change how much it zooms in by to try and mitigate the chance of rounding errors. I will experiment, I think we are using `1/1.4` at the moment

**Comment by cjcolvar** [comment]
@stephenwf How about merging this PR now and have a followup PR for the bubble selection highlight rendering issue I mentioned above?

**Comment by stephenwf** [comment]
Sounds good 👍

**Pull request merged**
