### PR TITLE
Feature/add zoom to selection

### LINKED ISSUE #278: Selecting 2 bubbles to group them is zooming in
We are supposed to zoom in only the user requests it by clicking on the correct icon/gadget/button.

### PR DESCRIPTION
**Pull request by stephenwf**
closes #278

### CODE REVIEW

**Comment by cjcolvar** [comment]
Is the plan to expose the `zoomTowards` saga in the interface anywhere or just add the functionality as a phase 1?

**Comment by stephenwf** [comment]
So currently how this work is:

* When you are at a specific position in the timeline, when you zoom it will zoom towards the point in time you are at.
* If you have selected a group of bubbles, when you click zoom it will zoom in to fit all of the bubbles.

There is a hidden setting that will stop the behaviour of zooming all the way into the bubbles you've selected, instead zooming by a set amount of zoom (like normal) but zooming towards your selection and ensuring it stays in view.

**Comment by cjcolvar** [comment]
Since this is a behavior thing, I'm going to let @ mcwhitaker and @joncameron sign off on it.  Technically it seems fine to me.

**Comment by mcwhitaker** [comment]
I am fine with the current behavior. Let's see what @joncameron says.

**Comment by joncameron** [comment]
The behavior described sounds good to me.

**Pull request merged**
